FROM ubuntu

# Replace mirrors, see http://askubuntu.com/questions/39922/how-do-you-select-the-fastest-mirror-from-the-command-line/9035#9035
#RUN sed -i -e 's#http://archive.ubuntu.com/ubuntu#mirror://mirrors.ubuntu.com/mirrors.txt#g' /etc/apt/sources.list

RUN apt-get update && apt-get upgrade -y # last updated 2014-05-01

